FROM ubuntu AS builder
ENV JAVA_HOME=/usr/lib/jvm/default-java
COPY . /usr/src/validator/
WORKDIR /usr/src/validator
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt update && apt upgrade -y \
    && apt install --no-install-recommends -y \
            default-jdk \
            python3 \
            git \
    && update-alternatives --auto java \
    && python3 ./checker.py dldeps \
    && python3 ./checker.py build \
    && python3 ./checker.py image \
    && python3 ./checker.py check \
    && python3 ./checker.py test

FROM alpine
# to use:
# docker build -t validator/validator .
# docker run -it --rm \
#    -e CONNECTION_TIMEOUT_SECONDS=15 \
#    -e SOCKET_TIMEOUT_SECONDS=15 \
#    -p 8888:8888 \
#    validator/validator
LABEL name="vnu"
LABEL version="dev"
LABEL maintainer="Michael[tm] Smith <mike@w3.org>"
COPY --from=builder /usr/src/validator/build/dist/vnu.linux.zip /usr/src/validator/build/dist/vnu.linux.zip.sha1 ./
SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
RUN apk upgrade --no-cache -U -a && \
    apk add --no-cache unzip && \
    echo "$(cat vnu.linux.zip.sha1)  vnu.linux.zip" | sha1sum -c - && \
    unzip ./vnu.linux.zip && \
    rm ./vnu.linux.zip* && \
    apk del --purge -r unzip
ENV LANG C.UTF-8
ENV JAVA_TOOL_OPTIONS ""
ENV CONNECTION_TIMEOUT_SECONDS 5
ENV SOCKET_TIMEOUT_SECONDS 5
ENV BIND_ADDRESS 0.0.0.0
ENV PATH=/vnu-runtime-image/bin:$PATH
EXPOSE 8888
# hadolint ignore=DL3025
CMD CONNECTION_TIMEOUT=$((CONNECTION_TIMEOUT_SECONDS * 1000)); \
    SOCKET_TIMEOUT=$((SOCKET_TIMEOUT_SECONDS * 1000)); \
    ./vnu-runtime-image/bin/java \
    -Dnu.validator.servlet.connection-timeout=$CONNECTION_TIMEOUT \
    -Dnu.validator.servlet.socket-timeout=$SOCKET_TIMEOUT \
    -Dnu.validator.servlet.bind-address=$BIND_ADDRESS \
    -m vnu/nu.validator.servlet.Main 8888
