name: 'Update GitHub Release'
description: 'Upload a release asset to a GitHub Release'
author: 'Umoxfo'

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  tag_name:
    description: 'Name of the tag of this release'
    required: true
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
    required: false
    default: false
  file:
    description: 'Local file to upload'
    required: true
  asset_name:
    description: 'Name of the asset'
    required: true
  asset_content_type:
    description: 'The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information. Default: `application/octet-stream`'
    required: false
    default: 'application/octet-stream'
  overwrite:
    description: 'Overwrite the release in case it already exists. Default: `false`'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'lib/index.js'
